#!/usr/bin/env bash
set -ue
DN="$(readlink -f "$(dirname "${0}")")"
. "${DN}/exec/libisopt.sh"
# ============ Possess arguments ============

STDS=()
for opt in "${@}"; do
    if isopt "${opt}"; then
        case "${opt}" in
        "-h" | "--help")
            echo "Help should be added here."
            exit 0
            ;;
        *)
        	STDS=("${STDS[@]}" "${opt}")
        	;;
        esac
    else
        STDS=("${STDS[@]}" "${opt}")
    fi
done
cmd="${STDS[0]:-}"
unset STDS[0]
if [ -z "${cmd}" ]; then
	echo -e "\e[31mERROR: Subcommand not provided. Use 'bioxp list' to get all subcommands.\e[0m"
    exit 1
elif [ -e "${DN}"/exec/bioxp_"${cmd}".sh ];then
    bash "${DN}"/exec/bioxp_"${cmd}".sh "${STDS[@]}"
else
    echo -e "\e[31mERROR: Subcommand '${cmd}' invalid!\e[0m"
    exit 1
fi
